// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TheBindery.Infrastructure.EFCore.SqlServer;

namespace TheBindery.Infrastructure.EFCore.SqlServer.Migrations
{
    [DbContext(typeof(TheBinderyDataContext))]
    [Migration("20180917162855_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TheBindery.Domain.Agreggates.TheBinderyContent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ContentParagraph");

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.ToTable("TheBinderyContent");

                    b.HasDiscriminator<string>("Discriminator").HasValue("TheBinderyContent");
                });

            modelBuilder.Entity("TheBindery.Domain.Agreggates.Event.Event", b =>
                {
                    b.HasBaseType("TheBindery.Domain.Agreggates.TheBinderyContent");


                    b.ToTable("Event");

                    b.HasDiscriminator().HasValue("Event");
                });

            modelBuilder.Entity("TheBindery.Domain.Agreggates.GalleryImage.GalleryImage", b =>
                {
                    b.HasBaseType("TheBindery.Domain.Agreggates.TheBinderyContent");

                    b.Property<string>("Author");

                    b.ToTable("GalleryImage");

                    b.HasDiscriminator().HasValue("GalleryImage");
                });

            modelBuilder.Entity("TheBindery.Domain.Agreggates.News.News", b =>
                {
                    b.HasBaseType("TheBindery.Domain.Agreggates.TheBinderyContent");

                    b.Property<string>("Author")
                        .HasColumnName("News_Author");

                    b.Property<DateTime?>("NewsDate");

                    b.Property<string>("Section");

                    b.ToTable("News");

                    b.HasDiscriminator().HasValue("News");
                });
#pragma warning restore 612, 618
        }
    }
}
